// Generated by Selenium IDE
package com.tomas.ua.airquality;

import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.JavascriptExecutor;
import java.util.*;
import java.net.URL;

public class TestlisbonTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    System.setProperty("webdriver.chrome.driver","chromedriver");
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void testlisbon() {
    // Test name: test-lisbon
    // Step # | name | target | value
    // 1 | open | / | 
    driver.get("http://localhost:8080/madrid/");
    // 2 | setWindowSize | 1920x1043 | 
    driver.manage().window().setSize(new Dimension(1920, 1043));
    // 3 | assertText | css=.card-title > span | Entrecampos, Lisboa, Portugal
    assertThat(driver.findElement(By.cssSelector(".card-title > span")).getText(), is("Entrecampos, Lisboa, Portugal"));
    // 4 | assertElementPresent | css=li:nth-child(3) > b | 
    {
      List<WebElement> elements = driver.findElements(By.cssSelector("li:nth-child(3) > b"));
      assert(elements.size() > 0);
    }
    // 5 | verifyElementPresent | css=li:nth-child(1) > b | 
    {
      List<WebElement> elements = driver.findElements(By.cssSelector("li:nth-child(1) > b"));
      assert(elements.size() > 0);
    }
    // 6 | verifyText | css=.m-0 | Lisbon
    assertThat(driver.findElement(By.cssSelector(".m-0")).getText(), is("Lisbon"));
    // 7 | verifyTitle | AirQuality | 
    assertThat(driver.getTitle(), is("AirQuality"));
  }
}
