// Generated by Selenium IDE
package com.tomas.ua.airquality;

import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.JavascriptExecutor;
import java.util.*;

public class TestmadridTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    System.setProperty("webdriver.chrome.driver","chromedriver");
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void testmadrid() {
    // Test name: test-madrid
    // Step # | name | target | value
    // 1 | open | http://localhost:8080/madrid | 
    driver.get("http://localhost:8080/madrid");
    // 2 | setWindowSize | 1440x713 | 
    driver.manage().window().setSize(new Dimension(1440, 713));
    // 3 | assertText | css=.card-title > span | Madrid
    assertThat(driver.findElement(By.cssSelector(".card-title > span")).getText(), is("Madrid"));
    // 4 | verifyText | css=.m-0 | Madrid
    assertThat(driver.findElement(By.cssSelector(".m-0")).getText(), is("Madrid"));
    // 5 | assertElementPresent | css=li:nth-child(1) > b | 
    {
      List<WebElement> elements = driver.findElements(By.cssSelector("li:nth-child(1) > b"));
      assert(elements.size() > 0);
    }
    // 6 | assertElementPresent | css=li:nth-child(1) > span | 
    {
      List<WebElement> elements = driver.findElements(By.cssSelector("li:nth-child(1) > span"));
      assert(elements.size() > 0);
    }
    // 7 | assertElementPresent | css=li:nth-child(3) > b | 
    {
      List<WebElement> elements = driver.findElements(By.cssSelector("li:nth-child(3) > b"));
      assert(elements.size() > 0);
    }
    // 8 | verifyElementPresent | css=li:nth-child(8) > b | 
    {
      List<WebElement> elements = driver.findElements(By.cssSelector("li:nth-child(8) > b"));
      assert(elements.size() > 0);
    }
  }
}
